"""Proxy exposure plugin — Rust userspace L4 daemon.

Replaces the envoy plugin entirely. The plugin's job here is
narrow:

1. Translate the agent's per-network service set into HMAC-signed
   catalog entries on disk. The Rust ``nls-proxy`` worker watches
   the catalog file via inotify and reconciles its listener set
   accordingly.

2. Tell ``nls-proxy`` (via the worker's control socket) about the
   tenant netns when it appears, so the worker can spawn its
   per-tenant data-path thread. The agent has already opened the
   netns fd via the priv helper at netns-create time; the agent
   passes that fd to the worker via SCM_RIGHTS.

3. Maintain a per-network nonce file that the priv helper
   verifies post-``setns()`` before binding listeners.

4. Scrape the worker's admin endpoint (``/clusters?format=json``) to
   surface backend health back to the registry API. The shape mirrors
   envoy's so the existing ``get_backend_health`` parser keeps
   working.

The plugin does NOT spawn the proxy. Both ``nls-proxy-priv`` and
``nls-proxy`` run as long-lived systemd services (one process pair
per chassis). The plugin just publishes config and registers /
deregisters tenant netns.

State on disk (under ``/var/lib/neutron-local-services/_proxy/``):
    catalog.json           — atomic-rename target the worker watches
    hmac.key               — per-boot HMAC-SHA256 key (mode 0400)
    admin.token            — bearer token for admin scrapes (0400)
    nonces/<network_id>    — per-network nonce file, contents echoed in catalog

The worker reads ``hmac.key`` and ``admin.token`` once at startup;
this plugin reads them on every apply to sign / scrape.
"""

import errno
import json
import os
import secrets
import shutil
import socket
import struct
import threading
import urllib.request

from oslo_log import log as logging

from neutron_local_services import constants as lsc
from neutron_local_services.agent.plugins import base


LOG = logging.getLogger(__name__)

# Paths shared with the Rust worker. Kept in lockstep with
# proxy/worker/src/main.rs DEFAULT_* constants and with the systemd
# units installed by the devstack plugin. Change one, change all.
PROXY_STATE_DIR = '/var/lib/neutron-local-services/_proxy'
CATALOG_PATH = os.path.join(PROXY_STATE_DIR, 'catalog.json')
HMAC_KEY_PATH = os.path.join(PROXY_STATE_DIR, 'hmac.key')
ADMIN_TOKEN_PATH = os.path.join(PROXY_STATE_DIR, 'admin.token')
NONCE_DIR = os.path.join(PROXY_STATE_DIR, 'nonces')

PROXY_RUN_DIR = '/var/run/neutron-local-services/_proxy'
CONTROL_SOCKET = os.path.join(PROXY_RUN_DIR, 'control.sock')
ADMIN_SOCKET = os.path.join(PROXY_RUN_DIR, 'admin.sock')
# Worker writes its boot-id (timestamp+pid) to this file at startup.
# We compare on every reconcile and clear the AddNetns cache if it
# changed, so a worker restart triggers re-registration. Without
# this, the worker comes up with no per-tenant data-path threads
# and no listeners, while the agent thinks everything is fine.
BOOT_ID_PATH = os.path.join(PROXY_RUN_DIR, 'worker.boot')

# Bumped whenever a non-noop catalog write happens. The worker
# rejects regressions so a stale rewrite (e.g., concurrent reconcile)
# can't trigger a downgrade. We seed lazily from the existing catalog
# file so an agent restart doesn't reset the counter behind a
# still-running worker (the worker keeps its in-memory `cur` and
# would otherwise reject our new writes as regressions).
_GENERATION_LOCK = threading.Lock()
_GENERATION = None


def _seed_generation_from_disk():
    try:
        with open(CATALOG_PATH, 'rb') as fh:
            data = fh.read()
        nl = data.index(b'\n')
        payload = json.loads(data[nl + 1:])
        return int(payload.get('generation', 0))
    except (OSError, ValueError, KeyError):
        return 0


def _next_generation():
    global _GENERATION
    with _GENERATION_LOCK:
        if _GENERATION is None:
            _GENERATION = _seed_generation_from_disk()
        _GENERATION += 1
        return _GENERATION


def _read_or_create_hmac_key():
    """Read the per-boot HMAC key, generating one if missing.

    The worker reads this once at startup so a key rotation requires
    restarting both worker and any plugins. For the PoC we generate
    on first use; production wiring should derive from a host secret
    (e.g., systemd-creds) and not be regenerated by the agent.
    """
    if os.path.isfile(HMAC_KEY_PATH):
        with open(HMAC_KEY_PATH, 'rb') as fh:
            return fh.read()
    os.makedirs(PROXY_STATE_DIR, mode=0o755, exist_ok=True)
    key = secrets.token_bytes(32)
    fd = os.open(HMAC_KEY_PATH,
                 os.O_WRONLY | os.O_CREAT | os.O_EXCL,
                 mode=0o400)
    try:
        os.write(fd, key)
    finally:
        os.close(fd)
    return key


def _read_or_create_admin_token():
    if os.path.isfile(ADMIN_TOKEN_PATH):
        with open(ADMIN_TOKEN_PATH) as fh:
            return fh.read().strip()
    os.makedirs(PROXY_STATE_DIR, mode=0o755, exist_ok=True)
    token = secrets.token_urlsafe(32)
    fd = os.open(ADMIN_TOKEN_PATH,
                 os.O_WRONLY | os.O_CREAT | os.O_EXCL,
                 mode=0o400)
    try:
        os.write(fd, token.encode())
        os.write(fd, b'\n')
    finally:
        os.close(fd)
    return token


def _ensure_nonce(network_id):
    """Return the nonce path + contents for ``network_id``.

    Creates a fresh random nonce on first call. Subsequent calls
    return the existing one — the priv helper's verification only
    cares that the catalog entry's nonce matches the file content.
    """
    os.makedirs(NONCE_DIR, mode=0o700, exist_ok=True)
    path = os.path.join(NONCE_DIR, network_id)
    if os.path.isfile(path):
        with open(path) as fh:
            return path, fh.read().strip()
    nonce = secrets.token_hex(16)
    tmp = path + '.tmp'
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode=0o400)
    try:
        os.write(fd, nonce.encode())
    finally:
        os.close(fd)
    os.replace(tmp, path)
    return path, nonce


def _drop_nonce(network_id):
    path = os.path.join(NONCE_DIR, network_id)
    try:
        os.remove(path)
    except FileNotFoundError:
        pass


# Lookup of registry-side enums to the worker's catalog vocabulary.
_LB_ALGO = {
    lsc.DIST_ROUND_ROBIN: 'wrr',
    lsc.DIST_LEAST_CONNECTION: 'least_conn',
    lsc.DIST_ACTIVE_BACKUP: 'wrr',  # worker has no active-backup;
                                    # weights emulate, see PLAN open Qs.
}

# HC type translation. The worker supports a closed set of native
# probes: tcp_connect, http_get, https_handshake, udp_dns_query,
# udp_ntp_query. There is intentionally no path-execution variant on
# the wire — the API surface (HC_TYPES) and the catalog schema agree
# on this set, so a tampered or buggy catalog cannot ask the worker
# to fork-exec an attacker-named binary.


def _hc_for_service(svc):
    """Translate the registry's HC fields into the worker's catalog
    health_check object."""
    hc_type = svc.get('health_check_type') or lsc.HC_NONE
    if hc_type == lsc.HC_NONE:
        return {'type': 'tcp_connect'}  # cheapest default
    if hc_type == lsc.HC_TCP:
        return {'type': 'tcp_connect'}
    if hc_type == lsc.HC_HTTP:
        return {'type': 'http_get', 'path': '/'}
    if hc_type == lsc.HC_HTTPS:
        return {'type': 'https_handshake'}
    if hc_type == lsc.HC_DNS:
        return {'type': 'udp_dns_query'}
    if hc_type == lsc.HC_NTP:
        return {'type': 'udp_ntp_query'}
    return {'type': 'tcp_connect'}


def _expand_protocols(svc):
    """A tcp-udp service renders as one entry per protocol."""
    proto = svc.get('protocol')
    if proto == lsc.PROTO_TCP_UDP:
        return [lsc.PROTO_TCP, lsc.PROTO_UDP]
    if proto in (lsc.PROTO_TCP, lsc.PROTO_UDP):
        return [proto]
    return []


def _entry_for(network_id, svc, proto, nonce_path, nonce):
    backends = []
    for b in svc.get('backends') or []:
        if not b.get('enabled', True):
            continue
        addr = b.get('address')
        port = b.get('port')
        if not addr or not port:
            continue
        weight = b.get('weight')
        if not isinstance(weight, int) or weight <= 0:
            weight = 1
        backends.append({'addr': addr, 'port': int(port), 'weight': weight})
    return {
        'net_id': network_id,
        'service_id': svc['id'],
        'nonce': nonce,
        'nonce_path': nonce_path,
        'vip': svc['local_ipv4'],
        'port': int(svc['port']),
        'proto': proto,
        'backends': backends,
        'health_check': _hc_for_service(svc),
        'lb_algo': _LB_ALGO.get(
            svc.get('distribution_policy') or lsc.DIST_ROUND_ROBIN,
            'wrr'),
        'max_concurrent': 1000,
        'max_session_idle_s': 60,
    }


def _hmac_sha256(key, payload):
    import hmac as hmac_mod
    import hashlib
    return hmac_mod.new(key, payload, hashlib.sha256).hexdigest()


def _write_catalog_atomic(entries):
    key = _read_or_create_hmac_key()
    payload = {
        'version': 1,
        'generation': _next_generation(),
        'entries': entries,
    }
    payload_bytes = json.dumps(payload, separators=(',', ':'),
                               sort_keys=True).encode('utf-8')
    sig = _hmac_sha256(key, payload_bytes)
    body = sig.encode('ascii') + b'\n' + payload_bytes
    os.makedirs(PROXY_STATE_DIR, mode=0o755, exist_ok=True)
    tmp = CATALOG_PATH + '.tmp'
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode=0o644)
    try:
        os.write(fd, body)
    finally:
        os.close(fd)
    os.replace(tmp, CATALOG_PATH)


def _send_control(req):
    """Send a single control RPC (length-prefixed JSON; no SCM_RIGHTS).

    Returns the decoded response dict. Raises on socket error / decode
    error. The fd-attached forms are handled separately because Python
    needs ``socket.sendmsg`` for ancillary data.
    """
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.connect(CONTROL_SOCKET)
        body = json.dumps(req).encode()
        s.sendall(struct.pack('>I', len(body)) + body)
        hdr = _recv_exactly(s, 4)
        n = struct.unpack('>I', hdr)[0]
        return json.loads(_recv_exactly(s, n))
    finally:
        s.close()


def _send_control_with_fd(req, fd):
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        s.connect(CONTROL_SOCKET)
        body = json.dumps(req).encode()
        # Mirror the Rust scm crate's wire layout: length prefix in
        # one sendmsg WITHOUT cmsgs, body in a second sendmsg WITH
        # the SCM_RIGHTS attachment. Linux unix(7) attaches the
        # cmsg to the first byte of the sendmsg's data; bundling
        # length + body in one call would deliver the cmsg with the
        # length prefix and the worker rejects fds in that recv.
        s.sendall(struct.pack('>I', len(body)))
        s.sendmsg(
            [body],
            [(socket.SOL_SOCKET, socket.SCM_RIGHTS,
              struct.pack('i', fd))])
        hdr = _recv_exactly(s, 4)
        n = struct.unpack('>I', hdr)[0]
        return json.loads(_recv_exactly(s, n))
    finally:
        s.close()


def _recv_exactly(s, n):
    out = bytearray()
    while len(out) < n:
        chunk = s.recv(n - len(out))
        if not chunk:
            raise IOError('eof from worker control socket')
        out.extend(chunk)
    return bytes(out)


def _open_tenant_netns_fd(network_id):
    """Open the tenant netns and return an `O_RDONLY|O_CLOEXEC|O_NOFOLLOW`
    fd (caller closes).

    `/run/netns/<name>` is a bind-mount of `/proc/<pid>/ns/net` created by
    `ip netns add`. The agent already owns the netns lifecycle (see
    `agent/netns.py`), so it has the file-system access to open the fd
    directly — there's no privilege the priv helper would add. Routing
    netns opens through priv was a leftover from the original RPC
    catalog and removed for the smaller attack surface.
    """
    netns_name = lsc.NETNS_PREFIX + network_id
    path = '/run/netns/' + netns_name
    return os.open(path, os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW)


# Cache of (network_id → True) for tenants we've already registered
# with the worker. The worker rejects double-add, so we serialize and
# track here to avoid log-spam. Keyed under the worker's current
# boot-id so a worker restart drops the cache and we re-register.
_REGISTERED_LOCK = threading.Lock()
_REGISTERED = set()
_REGISTERED_BOOT_ID = None


def _read_worker_boot_id():
    try:
        with open(BOOT_ID_PATH) as fh:
            return fh.read().strip() or None
    except (OSError, ValueError):
        return None


def _check_worker_restart_locked():
    """Drop the cache if the worker's boot-id changed.

    Caller holds _REGISTERED_LOCK.
    """
    global _REGISTERED_BOOT_ID
    cur = _read_worker_boot_id()
    if cur is None:
        # Worker hasn't written yet, or run dir is gone. Treat as
        # "unknown"; don't clear cache speculatively but also don't
        # update _REGISTERED_BOOT_ID, so the next call re-checks.
        return
    if cur != _REGISTERED_BOOT_ID:
        if _REGISTERED:
            LOG.info('proxy plugin: worker boot-id changed (%s -> %s); '
                     'clearing AddNetns cache so we re-register all '
                     'tenant netns', _REGISTERED_BOOT_ID, cur)
        _REGISTERED.clear()
        _REGISTERED_BOOT_ID = cur


def _ensure_registered(network_id):
    with _REGISTERED_LOCK:
        _check_worker_restart_locked()
        if network_id in _REGISTERED:
            return
    fd = _open_tenant_netns_fd(network_id)
    try:
        resp = _send_control_with_fd(
            {'op': 'add_netns', 'net_id': network_id}, fd)
    finally:
        os.close(fd)
    if resp.get('result') == 'ok':
        with _REGISTERED_LOCK:
            _REGISTERED.add(network_id)
        return
    msg = resp.get('msg', '')
    if 'already registered' in msg:
        with _REGISTERED_LOCK:
            _REGISTERED.add(network_id)
        return
    raise RuntimeError('worker AddNetns failed: %s' % msg)


def _ensure_deregistered(network_id):
    try:
        resp = _send_control({'op': 'remove_netns', 'net_id': network_id})
    except (FileNotFoundError, ConnectionRefusedError):
        # Worker is down; nothing to deregister. The next worker
        # start sees no entries for this net_id and idles.
        return
    if resp.get('result') != 'ok':
        # "not registered" is fine — defensive no-op.
        msg = resp.get('msg', '')
        if 'not registered' not in msg:
            LOG.warning('worker RemoveNetns(%s) returned %r',
                        network_id, resp)
    with _REGISTERED_LOCK:
        _REGISTERED.discard(network_id)


# In-process serialization. Same reason as the LVS plugin: the
# reconciler can fire from three places concurrently.
_apply_locks = {}
_apply_locks_guard = threading.Lock()


def _apply_lock_for(network_id):
    with _apply_locks_guard:
        lock = _apply_locks.get(network_id)
        if lock is None:
            lock = threading.Lock()
            _apply_locks[network_id] = lock
        return lock


def _drop_apply_lock(network_id):
    with _apply_locks_guard:
        _apply_locks.pop(network_id, None)


# Per-network slice cached so we can write the union catalog every
# apply (single file, all networks, atomic rename). Keys are
# network_id.
_NETWORK_SLICES_LOCK = threading.Lock()
_NETWORK_SLICES = {}


def _set_slice(network_id, entries):
    with _NETWORK_SLICES_LOCK:
        if entries:
            _NETWORK_SLICES[network_id] = entries
        else:
            _NETWORK_SLICES.pop(network_id, None)


def _all_entries_snapshot():
    with _NETWORK_SLICES_LOCK:
        out = []
        for entries in _NETWORK_SLICES.values():
            out.extend(entries)
        return out


class ProxyPlugin(base.ExposurePlugin):
    """Rust L4 proxy plugin. Selected by ``exposure_plugin=proxy``."""

    name = lsc.EXPOSURE_PROXY

    def apply_config(self, netns_name, services):
        if not netns_name.startswith(lsc.NETNS_PREFIX):
            LOG.warning('proxy plugin: unexpected netns name %s; skipping',
                        netns_name)
            return
        network_id = netns_name[len(lsc.NETNS_PREFIX):]
        with _apply_lock_for(network_id):
            self._apply_locked(network_id, services)

    def _apply_locked(self, network_id, services):
        nonce_path, nonce = _ensure_nonce(network_id)
        entries = []
        for svc in services:
            if not svc.get('enabled', True):
                continue
            if not svc.get('local_ipv4') or not svc.get('port'):
                continue
            # The worker rejects catalog entries with no backends
            # (validation bails the whole catalog). Skip until at
            # least one backend exists; the next reconcile after the
            # backend POST will re-emit the entry.
            if not [b for b in (svc.get('backends') or []) if b.get('enabled', True)]:
                continue
            for proto in _expand_protocols(svc):
                entries.append(_entry_for(
                    network_id, svc, proto, nonce_path, nonce))
        _set_slice(network_id, entries)
        _write_catalog_atomic(_all_entries_snapshot())
        if entries:
            try:
                _ensure_registered(network_id)
            except Exception:
                LOG.exception(
                    'proxy plugin: AddNetns(%s) failed; the worker '
                    'will pick up listeners on the next AddNetns retry',
                    network_id)

    def teardown(self, netns_name):
        if not netns_name.startswith(lsc.NETNS_PREFIX):
            return
        network_id = netns_name[len(lsc.NETNS_PREFIX):]
        _set_slice(network_id, [])
        try:
            _write_catalog_atomic(_all_entries_snapshot())
        except OSError as exc:
            if exc.errno != errno.ENOENT:
                LOG.exception('catalog rewrite at teardown')
        _ensure_deregistered(network_id)
        _drop_nonce(network_id)
        _drop_apply_lock(network_id)

    def get_backend_health(self, netns_name, service_id, backend_id):
        try:
            data = _scrape_clusters_json()
        except Exception:
            LOG.debug('proxy plugin: /clusters scrape failed', exc_info=True)
            return 'unknown'
        for cluster in data.get('cluster_statuses', []):
            if cluster.get('name') != service_id:
                continue
            for host in cluster.get('host_statuses', []):
                addr = (host.get('address', {})
                        .get('socket_address', {})
                        .get('address'))
                port = (host.get('address', {})
                        .get('socket_address', {})
                        .get('port_value'))
                # backend_id from the registry is opaque; here we
                # match on (addr, port) which the catalog round-trips.
                if str(backend_id) in (str(addr), '%s:%s' % (addr, port)):
                    eds = (host.get('health_status', {})
                           .get('eds_health_status'))
                    if eds == 'HEALTHY':
                        return 'up'
                    if eds == 'UNHEALTHY':
                        return 'down'
                    return 'unknown'
        return 'unknown'

    def get_stats(self, netns_name):
        # Aggregated metrics live behind /metrics. Returning an empty
        # dict here keeps the abstract surface satisfied; the registry
        # API can scrape /metrics directly when it wants quantitative
        # data (PoC: skip).
        return {}


def _scrape_clusters_json():
    """Fetch ``/clusters?format=json`` from the worker admin socket."""
    token = _read_or_create_admin_token()
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect(ADMIN_SOCKET)
    try:
        req = (
            b'GET /clusters?format=json HTTP/1.1\r\n'
            b'Host: localhost\r\n'
            b'Authorization: Bearer ' + token.encode() + b'\r\n'
            b'Connection: close\r\n\r\n'
        )
        sock.sendall(req)
        chunks = []
        while True:
            chunk = sock.recv(4096)
            if not chunk:
                break
            chunks.append(chunk)
    finally:
        sock.close()
    raw = b''.join(chunks)
    sep = raw.find(b'\r\n\r\n')
    if sep < 0:
        raise IOError('no http body separator')
    body = raw[sep + 4:]
    return json.loads(body)


# Register on import.
base.register(ProxyPlugin)
